image: Visual Studio 2022

version: 0.1.{build}

skip_tags: true

configuration: Release

install:
  - choco install dotnet-sdk --version 8.0.100

branches:
  only:
  - main
  - development
  - feat/*
  - fix/*
  - test/*
  - refactor/*

before_build:
  - dotnet restore Ambev.DeveloperEvaluation.sln

build_script:
  - dotnet build Ambev.DeveloperEvaluation.sln --no-restore --configuration Release

test_script:
  - dotnet test Ambev.DeveloperEvaluation.sln --no-build --configuration Release --results-directory "test_results" --collect:"XPlat Code Coverage;Format=cobertura"

artifacts:
  - path: test_results/*/coverage.cobertura.xml